name: pazu
favicon: null
layout_spectrum: 0.51091
typography_spectrum: 0.12053770921193063
title: the pazu website
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000c00'
    - '#004e40'
    - '#8ab78c'
    - '#53602a'
  brandStrength: 0.6807750454172492
  lightness: 0.7597926335874945
  saturation: 0.6659022576641291
  rhythmicContrast: 0.08476271806284785
purpose: []
